GET http://localhost:8080/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiYWNjZXNzIiwic3ViIjoidHVkb3JAdXRjbi5ybyIsImlhdCI6MTc3NjUyNDAxNSwiZXhwIjoxNzc2NTI0OTE1LCJqdGkiOiIwNjE0NGFhNS0zOGZlLTQyYzktOGUyYi01NzMyNjMzMWY5NzUifQ.he9AlYxYWLjJmiUQXuoITUwmpu4lfPKu3d4WwXc-tWs
